# SPDX-FileCopyrightText: 2026 Noyalib
# SPDX-License-Identifier: MIT OR Apache-2.0
homepage: "https://github.com/sebastienrousseau/noyalib"
main_repo: "https://github.com/sebastienrousseau/noyalib"
language: rust
primary_contact: "sebastian.rousseau@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs: []
