
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.ahash]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.annotate-snippets]]
version = "0.12.15"
criteria = "safe-to-deploy"

[[exemptions.bytecount]]
version = "0.6.9"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.fraction]]
version = "0.15.4"
criteria = "safe-to-deploy"

[[exemptions.granit-parser]]
version = "0.0.2"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.7.1"
criteria = "safe-to-run"

[[exemptions.hashlink]]
version = "0.9.1"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.inlinable_string]]
version = "0.1.15"
criteria = "safe-to-deploy"

[[exemptions.libyaml-safer]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.memmap2]]
version = "0.9.10"
criteria = "safe-to-run"

[[exemptions.num-cmp]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.owo-colors]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.proptest]]
version = "1.11.0"
criteria = "safe-to-run"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-deploy"

[[exemptions.rust-yaml]]
version = "0.0.5"
criteria = "safe-to-run"

[[exemptions.rusty-fork]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.serde-saphyr]]
version = "0.0.26"
criteria = "safe-to-deploy"

[[exemptions.serde_yaml_ng]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.yaml-rust2]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.yaml-spanned]]
version = "0.0.3"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.8.48"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.48"
criteria = "safe-to-deploy"
